services:
  - type: web
    name: ecommerce-electronics-api
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /api/health
    autoDeploy: true
